# Generated by Django 5.2.7 on 2025-10-17 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة')),
                ('grade', models.CharField(max_length=50, verbose_name='الصف')),
                ('deadline', models.DateTimeField(verbose_name='آخر موعد للتسليم')),
                ('max_students_per_group', models.IntegerField(default=1, verbose_name='عدد الطلاب في المجموعة')),
                ('max_file_size', models.IntegerField(default=100, verbose_name='الحد الأقصى لحجم الملف (MB)')),
                ('allowed_extensions', models.CharField(default='pdf,docx,xlsx', max_length=255, verbose_name='الامتدادات المسموحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'مشاريع',
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('student_id', models.CharField(max_length=50, verbose_name='رقم الطالب')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'طلاب',
                'db_table': 'students',
                'ordering': ['student_name'],
                'unique_together': {('project', 'student_id')},
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.project', verbose_name='المشروع')),
                ('students', models.ManyToManyField(related_name='groups', to='projects.student', verbose_name='الطلاب')),
            ],
            options={
                'verbose_name': 'مجموعة',
                'verbose_name_plural': 'مجموعات',
                'db_table': 'groups',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(verbose_name='حجم الملف (بايت)')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.group', verbose_name='المجموعة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.project', verbose_name='المشروع')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='projects.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسليم',
                'verbose_name_plural': 'تسليمات',
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
