# Generated by Django 5.0.7 on 2025-10-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_enhanced',
            field=models.BooleanField(default=False, verbose_name='محسّن بالذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='project',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='تعليمات المشروع'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_instructions',
            field=models.TextField(blank=True, null=True, verbose_name='التعليمات الأصلية'),
        ),
        migrations.AddField(
            model_name='project',
            name='original_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='الشروط الأصلية'),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True, null=True, verbose_name='شروط التسليم'),
        ),
        migrations.AddField(
            model_name='project',
            name='submission_duration',
            field=models.IntegerField(default=10, verbose_name='مدة التسليم (دقائق)'),
        ),
    ]
