# Generated by Django 5.0.7 on 2025-10-18 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_submission_validation_fields'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allowed_extensions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='project',
            name='max_students_per_group',
        ),
        migrations.RemoveField(
            model_name='project',
            name='original_instructions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='original_requirements',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section',
        ),
        migrations.RemoveField(
            model_name='project',
            name='submission_duration',
        ),
        migrations.AddField(
            model_name='project',
            name='ai_check_plagiarism',
            field=models.BooleanField(default=False, verbose_name='فحص الانتحال بالذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='project',
            name='allow_late_submission',
            field=models.BooleanField(default=False, verbose_name='السماح بالتسليم المتأخر'),
        ),
        migrations.AddField(
            model_name='project',
            name='allowed_file_types',
            field=models.JSONField(default=list, verbose_name='أنواع الملفات المسموحة'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_grade',
            field=models.IntegerField(default=100, verbose_name='الدرجة الكاملة'),
        ),
        migrations.AddField(
            model_name='project',
            name='sections',
            field=models.ManyToManyField(related_name='projects', to='sections.section', verbose_name='الشُعب'),
        ),
        migrations.AddField(
            model_name='project',
            name='send_reminder',
            field=models.BooleanField(default=True, verbose_name='إرسال تذكير'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البداية'),
        ),
        migrations.AddField(
            model_name='project',
            name='telegram_sent',
            field=models.BooleanField(default=False, verbose_name='تم الإرسال للتليجرام'),
        ),
        migrations.AddField(
            model_name='project',
            name='tips',
            field=models.TextField(blank=True, null=True, verbose_name='نصائح للطلاب'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='وصف المشروع'),
        ),
        migrations.AlterField(
            model_name='project',
            name='max_file_size',
            field=models.IntegerField(default=10, verbose_name='الحد الأقصى لحجم الملف (MB)'),
        ),
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('video', 'فيديو'), ('pdf', 'PDF'), ('doc', 'Office'), ('link', 'رابط خارجي')], max_length=20, verbose_name='نوع الملف')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='مسار الملف')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='حجم الملف (بايت)')),
                ('external_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط خارجي')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'ملف المشروع',
                'verbose_name_plural': 'ملفات المشروع',
                'db_table': 'project_files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
