# Generated by Django 5.0.7 on 2025-10-26 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_allowed_extensions_and_more'),
        ('sections', '0008_alter_schoolgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('success', models.BooleanField(default=False, verbose_name='نجح الإرسال')),
                ('details', models.TextField(verbose_name='التفاصيل')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='projects.project', verbose_name='المشروع')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_logs', to='sections.section', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'سجل إرسال Telegram',
                'verbose_name_plural': 'سجلات إرسال Telegram',
                'db_table': 'telegram_send_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
