# Generated by Django 5.0.7 on 2025-10-30 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_telegramsendlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_validation_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل التحقق بالذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_constraints',
            field=models.JSONField(blank=True, default=dict, help_text='مثال: {"max_size_mb": 50, "duration": {"min": 15, "max": 30}}', verbose_name='قيود الملف'),
        ),
        migrations.AddField(
            model_name='project',
            name='file_type',
            field=models.CharField(choices=[('video', 'فيديو'), ('pdf', 'PDF'), ('image', 'صور'), ('document', 'مستندات (Word/Excel/PPT)'), ('audio', 'صوت')], default='pdf', max_length=20, verbose_name='نوع الملف المطلوب'),
        ),
        migrations.AddField(
            model_name='project',
            name='max_attempts',
            field=models.IntegerField(default=5, verbose_name='الحد الأقصى للمحاولات'),
        ),
        migrations.AddField(
            model_name='project',
            name='plagiarism_threshold',
            field=models.IntegerField(default=50, verbose_name='نسبة التشابه المسموحة (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='validation_requirements',
            field=models.JSONField(blank=True, default=list, help_text='مثال: [{"type": "name_in_video", "location": "last_5_seconds"}]', verbose_name='متطلبات التحقق'),
        ),
        migrations.AddField(
            model_name='submission',
            name='ai_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='تقييم الذكاء الاصطناعي (0-100)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='attempt_number',
            field=models.IntegerField(default=1, verbose_name='رقم المحاولة'),
        ),
        migrations.AddField(
            model_name='submission',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء من المعالجة'),
        ),
        migrations.AddField(
            model_name='submission',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='مدة المعالجة (ثواني)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=list, verbose_name='أسباب الرفض'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_student_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الطالب'),
        ),
        migrations.AddField(
            model_name='submission',
            name='submitted_student_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الطالب'),
        ),
        migrations.AddField(
            model_name='submission',
            name='validation_results',
            field=models.JSONField(blank=True, default=dict, verbose_name='نتائج التحقق التفصيلية'),
        ),
        migrations.AddField(
            model_name='submission',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('processing', 'جاري التحليل'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('needs_review', 'يحتاج مراجعة يدوية')], default='pending', max_length=20, verbose_name='حالة التحقق'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('processing', 'جاري التحليل'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('needs_review', 'يحتاج مراجعة يدوية')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
