# Generated by Django 5.0.7 on 2025-10-18 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_ai_enhanced_project_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='اسم الطالب')),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='معرّف المستخدم في تيليجرام')),
                ('telegram_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='معرّف المحادثة في تيليجرام')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم في تيليجرام')),
                ('code', models.CharField(max_length=6, verbose_name='رمز OTP')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التحقق'), ('verified', 'تم التحقق'), ('used', 'مستخدم'), ('expired', 'منتهي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('attempts', models.IntegerField(default=0, verbose_name='عدد المحاولات')),
                ('max_attempts', models.IntegerField(default=5, verbose_name='أقصى عدد محاولات')),
                ('submit_token', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='رمز التسليم')),
                ('submit_token_expires', models.DateTimeField(blank=True, null=True, verbose_name='انتهاء رمز التسليم')),
                ('signed_payload', models.TextField(verbose_name='البيانات الموقعة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستخدام')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'رمز OTP',
                'verbose_name_plural': 'رموز OTP',
                'db_table': 'project_otp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('init', 'طلب رمز'), ('sent', 'إرسال رمز'), ('verify_attempt', 'محاولة تحقق'), ('verify_success', 'تحقق ناجح'), ('verify_failed', 'تحقق فاشل'), ('expired', 'انتهى'), ('used', 'استخدم')], max_length=20, verbose_name='الإجراء')),
                ('details', models.TextField(blank=True, null=True, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='otp_system.projectotp', verbose_name='OTP')),
            ],
            options={
                'verbose_name': 'سجل OTP',
                'verbose_name_plural': 'سجلات OTP',
                'db_table': 'otp_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='projectotp',
            index=models.Index(fields=['code'], name='project_otp_code_b1cc47_idx'),
        ),
        migrations.AddIndex(
            model_name='projectotp',
            index=models.Index(fields=['submit_token'], name='project_otp_submit__58fafb_idx'),
        ),
        migrations.AddIndex(
            model_name='projectotp',
            index=models.Index(fields=['status'], name='project_otp_status_92ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='projectotp',
            index=models.Index(fields=['created_at'], name='project_otp_created_3bd6cf_idx'),
        ),
    ]
