# Generated by Django 5.0.7 on 2025-10-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('instructions', 'تعليمات الاستلام'), ('benefits', 'فوائد النظام'), ('welcome', 'رسالة ترحيب')], max_length=20, verbose_name='نوع المحتوى')),
                ('generated_text', models.TextField(verbose_name='النص المُولد')),
                ('is_custom', models.BooleanField(default=False, verbose_name='معدّل يدوياً')),
                ('prompt_used', models.TextField(blank=True, verbose_name='Prompt المستخدم')),
                ('model_name', models.CharField(default='gemini-pro', max_length=50, verbose_name='اسم النموذج')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_content', to='accounts.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'محتوى AI',
                'verbose_name_plural': 'محتوى AI',
                'db_table': 'ai_generated_content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('elementary', 'ابتدائي'), ('middle', 'متوسط'), ('high', 'ثانوي')], max_length=20, verbose_name='المرحلة')),
                ('grade_number', models.IntegerField(verbose_name='رقم الصف')),
                ('school_name', models.CharField(max_length=200, verbose_name='اسم المدرسة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'صف دراسي',
                'verbose_name_plural': 'صفوف دراسية',
                'db_table': 'school_grades',
                'ordering': ['level', 'grade_number'],
                'unique_together': {('teacher', 'level', 'grade_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.IntegerField(verbose_name='رقم الشعبة')),
                ('section_name', models.CharField(max_length=50, verbose_name='اسم الشعبة')),
                ('total_students', models.IntegerField(default=0, verbose_name='عدد الطلاب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sections.schoolgrade', verbose_name='الصف')),
            ],
            options={
                'verbose_name': 'شعبة',
                'verbose_name_plural': 'شُعب',
                'db_table': 'sections',
                'ordering': ['grade', 'section_number'],
                'unique_together': {('grade', 'section_number')},
            },
        ),
        migrations.CreateModel(
            name='SectionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('whatsapp', 'واتساب'), ('telegram', 'تيليجرام'), ('both', 'كلاهما')], default='whatsapp', max_length=20, verbose_name='المنصة')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='رابط واتساب')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='رابط تيليجرام')),
                ('join_token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز الانضمام')),
                ('join_link', models.CharField(max_length=500, verbose_name='رابط الانضمام')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('view_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('join_count', models.IntegerField(default=0, verbose_name='عدد الانضمامات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='sections.section', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'رابط شعبة',
                'verbose_name_plural': 'روابط الشُعب',
                'db_table': 'section_links',
            },
        ),
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الثلاثي')),
                ('registered_via_link', models.BooleanField(default=True, verbose_name='سجل عبر الرابط')),
                ('joined_group', models.BooleanField(default=False, verbose_name='انضم للقروب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانضمام')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='sections.section', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'تسجيل طالب',
                'verbose_name_plural': 'تسجيلات الطلاب',
                'db_table': 'student_registrations',
                'ordering': ['-registered_at'],
                'unique_together': {('section', 'full_name')},
            },
        ),
    ]
