# Generated by Django 5.0.7 on 2025-10-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='اسم القروب')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram Chat ID')),
                ('invite_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='رابط الانضمام')),
                ('bot_username', models.CharField(default='SmartEduProjectBot', max_length=100, verbose_name='اسم البوت')),
                ('is_bot_added', models.BooleanField(default=False, verbose_name='هل البوت مضاف؟')),
                ('is_bot_admin', models.BooleanField(default=False, verbose_name='هل البوت مدير؟')),
                ('bot_permissions', models.JSONField(blank=True, default=dict, verbose_name='صلاحيات البوت')),
                ('permissions_applied', models.BooleanField(default=False, verbose_name='هل الصلاحيات مطبقة؟')),
                ('read_only_mode', models.BooleanField(default=True, verbose_name='وضع القراءة فقط')),
                ('instructions_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='معرف رسالة التعليمات')),
                ('instructions_sent', models.BooleanField(default=False, verbose_name='هل تم إرسال التعليمات؟')),
                ('instructions_pinned', models.BooleanField(default=False, verbose_name='هل تم تثبيت التعليمات؟')),
                ('status', models.CharField(choices=[('pending', 'قيد الإنشاء'), ('created', 'تم الإنشاء'), ('bot_added', 'تم إضافة البوت'), ('bot_admin', 'البوت مدير'), ('active', 'نشط'), ('inactive', 'غير نشط'), ('error', 'خطأ')], default='pending', max_length=20, verbose_name='الحالة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('members_count', models.IntegerField(default=0, verbose_name='عدد الأعضاء')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='عدد الرسائل المرسلة')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر رسالة')),
                ('created_by_phone', models.CharField(max_length=20, verbose_name='رقم هاتف المنشئ')),
                ('creation_metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_group', to='sections.section', verbose_name='الشعبة')),
            ],
            options={
                'verbose_name': 'قروب تيليجرام',
                'verbose_name_plural': 'قروبات تيليجرام',
                'db_table': 'telegram_groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
