# Generated by Django 5.0.7 on 2025-10-23 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_telegram_id_teacher_telegram_username'),
        ('sections', '0002_telegramgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherJoinLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_token', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رمز الرابط')),
                ('join_url', models.CharField(max_length=500, verbose_name='رابط الانضمام')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('registrations_count', models.IntegerField(default=0, verbose_name='عدد التسجيلات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'رابط انضمام المعلم',
                'verbose_name_plural': 'روابط انضمام المعلمين',
                'db_table': 'teacher_join_links',
            },
        ),
        # إزالة الحقول القديمة أولاً
        migrations.RemoveField(
            model_name='studentregistration',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='joined_group',
        ),
        migrations.RemoveField(
            model_name='studentregistration',
            name='registered_via_link',
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to='sections.schoolgrade', verbose_name='الصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='is_duplicate',
            field=models.BooleanField(default=False, verbose_name='تسجيل مكرر'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='joined_telegram',
            field=models.BooleanField(default=False, verbose_name='انضم للتليجرام'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='normalized_name',
            field=models.CharField(db_index=True, default=1, max_length=200, verbose_name='الاسم المعياري'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='original_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم الأصلي'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP المستخدم'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='school_name',
            field=models.CharField(default=1, max_length=200, verbose_name='اسم المدرسة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to='accounts.teacher', verbose_name='المعلم'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='telegram_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_students', to='sections.telegramgroup', verbose_name='قروب التليجرام'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='telegram_invite_link',
            field=models.URLField(blank=True, verbose_name='رابط القروب'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='معلومات المتصفح'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='full_name',
            field=models.CharField(max_length=200, verbose_name='الاسم الكامل'),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_students', to='sections.section', verbose_name='الشعبة'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['teacher', 'grade', 'section', 'normalized_name'], name='student_reg_teacher_2e761b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentregistration',
            index=models.Index(fields=['telegram_group'], name='student_reg_telegra_1bbe14_idx'),
        ),
        migrations.AddField(
            model_name='teacherjoinlink',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='join_link', to='accounts.teacher', verbose_name='المعلم'),
        ),
        # إضافة unique_together في النهاية بعد إضافة جميع الحقول
        migrations.AlterUniqueTogether(
            name='studentregistration',
            unique_together={('teacher', 'grade', 'section', 'normalized_name')},
        ),
    ]
