# Generated by Django 5.0.7 on 2025-10-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_teacherjoinlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherjoinlink',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='كلمة المرور'),
        ),
    ]
