# Generated by Django 5.0.7 on 2025-10-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0004_teacherjoinlink_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherjoinlink',
            name='password',
            field=models.CharField(blank=True, default=None, help_text='كلمة مرور اختيارية لحماية رابط الانضمام', max_length=100, null=True, verbose_name='كلمة المرور'),
        ),
    ]
