# Generated by Django 5.0.7 on 2025-10-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_add_password_to_join_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='telegram_invite_link',
            field=models.URLField(blank=True, default='', null=True, verbose_name='رابط القروب'),
        ),
    ]
