# Generated by Django 5.0.7 on 2025-10-23 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_subjects'),
        ('sections', '0006_fix_telegram_invite_link_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_phone', models.CharField(max_length=10, verbose_name='رقم جوال المعلم')),
                ('subject_name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='sections.schoolgrade', verbose_name='الصف')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_subjects', to='sections.section', verbose_name='الشعبة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_subjects', to='accounts.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'مادة معلم',
                'verbose_name_plural': 'مواد المعلمين',
                'db_table': 'teacher_subjects',
                'ordering': ['grade', 'section', 'subject_name'],
                'indexes': [models.Index(fields=['teacher', 'grade', 'section'], name='teacher_sub_teacher_eef691_idx'), models.Index(fields=['subject_name'], name='teacher_sub_subject_93ea2e_idx')],
                'unique_together': {('teacher', 'subject_name', 'grade', 'section')},
            },
        ),
    ]
