# Generated by Django 5.0.7 on 2025-10-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacher_subjects'),
        ('sections', '0007_teachersubject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolgrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolgrade',
            name='subject',
            field=models.CharField(default='غير محدد', help_text='مثال: المهارات الرقمية، الرياضيات، العلوم', max_length=100, verbose_name='المادة الدراسية'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolgrade',
            unique_together={('teacher', 'level', 'grade_number', 'subject')},
        ),
    ]
