# Generated by Django 5.0.7 on 2025-10-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_alter_schoolgrade_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='telegram_user_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram User ID'),
        ),
        migrations.AddField(
            model_name='studentregistration',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username'),
        ),
    ]
