# Generated by Django 5.2.7 on 2025-10-17 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=10, verbose_name='رقم الجوال')),
                ('school_name', models.CharField(max_length=200, verbose_name='اسم المدرسة')),
                ('password_hash', models.CharField(max_length=255, verbose_name='كلمة المرور المشفرة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخر تسجيل دخول')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلمون',
                'db_table': 'teachers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=10, verbose_name='رقم الجوال')),
                ('school_name', models.CharField(max_length=200, verbose_name='اسم المدرسة')),
                ('activation_code', models.CharField(max_length=6, verbose_name='كود التفعيل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الكود')),
            ],
            options={
                'verbose_name': 'معلم منتظر',
                'verbose_name_plural': 'معلمون منتظرون',
                'db_table': 'teachers_pending',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'فاتح'), ('dark', 'داكن')], default='light', max_length=10, verbose_name='السمة')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='اللغة')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.teacher', verbose_name='المعلم')),
            ],
            options={
                'verbose_name': 'إعدادات',
                'verbose_name_plural': 'إعدادات',
                'db_table': 'settings',
            },
        ),
    ]
