# Generated by Django 5.0.7 on 2025-10-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='معرف تيليجرام'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المستخدم في تيليجرام'),
        ),
    ]
