# Generated by Django 5.0.7 on 2025-10-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_telegram_id_teacher_telegram_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.JSONField(blank=True, default=list, help_text='قائمة المواد التي يدرسها المعلم', verbose_name='المواد الدراسية'),
        ),
    ]
